### ISSUE TITLE
Implementing GC milestone v4

### ISSUE THREAD

**Issue by tlively** [WebAssembly/binaryen#4149]
This is a tracking issue for implementing the new [milestone 4](https://docs.google.com/document/d/1afthjsL_B9UaMqCA5ekgVmOm75BVFu6duHNsN9-gnXw/edit?usp=sharing) GC spec. I plan to work through these starting with the new types but am happy to split up the work if anyone else wants to take some (cc @kripken).

## New features:

- [ ] New type definitions: `func_subtype`, `struct_subtype`, and `array_subtype`
    - [ ] Parsing and printing
    - [ ] Subtyping
    - [ ] LUB calculation
    - [ ] Integration into equirecursive canonicalization
- [ ] New allocation instructions: `struct.new{_default}`, `array.new_{default}`, and `array.init_static`
- [ ] New casting instructions: `ref.test_static`, `ref.cast_static`, `br_on_cast_static`, `br_on_cast_static_fail`

## Deprecating --nominal

Since the new milestone contains separate type definitions and instructions for dealing with nominal types, we will be able to remove our --nominal flag once users have stopped depending on it.

- [ ] Replace uses of `getTypeSystem` with a new `isNominal` method on `Type`
- [ ] Remove the --nominal flag

**Comment by kripken** [comment]
I'll look at the new instructions soon.

**Comment by tlively** [comment]
Writing down a more detailed transition plan for the types so that we can all agree that it makes sense. @kripken, let me know if this looks good to you.

## Downgrading to structural types

For the time being, we need to support downgrading nominal types to structural types to allow tests to run on infrastructure with older browser builds. This is currently done by running `wasm-opt` without --nominal again after optimizations are done with --nominal. That works because the parsers parse nominal types as structural types if --nominal is not passed. But that is incompatible with milestone 4, where nominal types need to be parsed as nominal types.

To preserve the ability to downgrade nominal types to structural types, we can introduce a new --structural flag that forces all types be parsed as equirecursive, just as the --nominal flag currently forces all types to be parsed as equirecursive. In the absence of --nominal or --structural, nominal types will be parsed as nominal and equirecursive types will be parsed as equirecursive.

Alternatively, we could implement a type replacement pass to downgrade all the types. That would be the technically superior solution, but this is a temporary migration mechanism and the --structural flag is both simpler to implement and closer to the current workflow.

## Text format migration

To gracefully transition to the new text format, we need to enable parsing it before we remove support for the old format. This can be done in stages to ensure proper test coverage:

1. Implement parsing the new format with identical semantics to the existing format. In other words, the new format will parse as nominal or equirecursive under the same conditions the existing format would parse as nominal or equirecursive. The only difference is that the new format additionally has the ability to express nominal types without nontrivial supertypes.

2. Update almost all tests to use the new format. Test input will no longer match test output at this stage, but there will be widespread test coverage for the parsing of the new format.

3. Update the printer to emit the new format. Test input will no longer match test output only for tests that explicitly test the old format.

4. Remove parser support and tests for the old format.

Alternatively, we could differentiate between the new and old formats in the binary format to preserve them through round trips. That would mean that only one of the old format or the new format could run on engines at any given time, though, so it would make the upgrade less graceful.

Another alternative would be to update the old format to support trivial supertypes and bring it up to feature parity with the new format as a first step. However, frontends would still need to update their printing to use the updated old format for nominal types with trivial supertypes, so we might as well have them upgrade entirely to the new format in one large step rather than a small step followed by a large step.

**Comment by tlively** [comment]
GC has been standardized and our support for it is stable.
